name: release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_semver: ${{ steps.semantic.outputs.new_release_git_tag }}

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs: semantic-release
    if: needs.semantic-release.outputs.release_published

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/gha-react-test
          labels: |
            org.opencontainers.image.title=gha-react-test
            org.opencontainers.image.description=A simple React Vite application, used to showcase GHA
            org.opencontainers.image.authors=Károly Szakály <karoly.szakaly2000@gmail.com>
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ needs.semantic-release.outputs.new_semver }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.semantic-release.outputs.new_semver }},prefix=v

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
